#!/usr/bin/env bash
VAR=date
SEL=$(xsel -o)
echo "$SEL" | md5sum | ascii85 > /tmp/$VAR
xclip -i "/tmp/$VAR" -selection clipboard
xdotool key ctrl+v
rm /tmp/$VAR
#zenity --text-info --width=500 --height=50 --title="Password generator" --filename=/tmp/$VAR
